#### 2D plot #####



#' @title  2D plot for genes.
#' @description  2D plots for genes.
#' The color of the data point represents the expression value of
#' a given gene in each sample.
#' @param data A data frame that contains the data to be visualized.
#' The data format is the same as the parameter 'data' in heartsvg and svg.clust.
#' It contains gene coordinates and gene expression counts.
#' @param gene A vector, the gene or list of genes to be plotted.
#' @param method he data processing method, which can be "raw" or "mean".
#' When set to "raw", the raw data of the specified genes will be plotted.
#' When set to "mean", the average expression values of the specified genes
#' in each sample will be plotted.
#' @param title A character string.An optional parameter for the title of the plot.
#' @param size point size.
#' @param log An optional parameter indicating whether to perform
#' a log transformation on the data, with a default value of F.
#' If set to T, the data will be transformed using log1p.
#' @return A 2D plot generated by the package ggplot2.
#' @export
#' 
#' 
svg.2Dplot=function(data,gene,method,title=NULL,size=0.5,log=F){
  ## method= mean/raw
  if(log==F){data=subset(data,select=c('row','col',gene))}
  if(log==T){data=cbind(subset(data,select=c('row','col')),
                        log1p(subset(data,select=c(gene))))}
  
  
  if(method=='raw'){
    for (g in gene) {
      g1=ggplot(data=data,aes(col,-row))+   ## aes(col,-row)可以和切片图像方向一致
        geom_point(aes(col=.data[[g]]),size=size)+
        scale_color_gradient(low = hsv(0.58,0.92,0.92),high = hsv(1,1,1))+
        labs(title=paste0('Gene: ',g))+
        xlab('col')+ylab('row')+
        theme_bw()+theme(panel.grid=element_blank(),panel.border=element_blank(),
                         axis.line=element_line(size=1,colour='black'))+
        theme(axis.title = element_blank(),
              axis.text = element_blank(),
              axis.ticks = element_blank(),
              axis.line = element_blank())
      
      print(g1)
    }
  }
  
  
  
  if(method=='mean'){
    if(is.null(title)){
      aa='Average expression'
    }
    if(!is.null(title)){
      aa=title
    }
    cl.data=subset(data,select = gene)  ## subset data with given gene 
    plot.cl=cbind(data[,1:2],apply(cl.data,1,function(z){mean(z,na.rm=T)}))   ## calculate mean expression
    colnames(plot.cl)[3]<-'cluster'
    g2=ggplot(data=plot.cl,aes(col,-row))+
      geom_point(aes(col=cluster),size=size)+
      scale_color_gradient(low = hsv(0.58,0.92,0.92),high = hsv(1,1,1),
                           name='value')+
      labs(title=aa)+
      xlab('col')+ylab('row')+
      theme_bw()+theme(panel.grid=element_blank(),panel.border=element_blank(),
                       axis.line=element_line(size=1,colour='black'))+
      theme(axis.title = element_blank(),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            axis.line = element_blank())
    print(g2)
  }
  
  
}




#' @title marginal plots for genes.
#' @param data A data frame that contains the data to be visualized.
#' The data format is the same as the parameter 'data' in heartsvg and svg.clust.
#' It contains gene coordinates and gene expression counts.
#' @param gene A vector, the gene or list of genes to be plotted.
#' @param method A character string for the drawing method,
#' with optional values of 'mean' or 'raw'.
#' If set to ‘mean’, it will calculate the average expression value of the
#' input gene set and plot the corresponding marginal expression plots
#' in the row and column directions. If set to ‘raw’, it will plot the
#' marginal expression plots of each gene in the input gene set
#' in the row and column directions.
#' @return  marginal plots along row and column directions for genes.
#' @export
svg.Mplot=function(data,gene,method='mean'){
  ## method= mean/raw
  if(method=='raw'){
    new=data.frame(data[,1:2],subset(data,select = gene))
    new.x=aggregate(new[,-c(1:2)],list(new$row),mean)
    new.y=aggregate(new[,-c(1:2)],list(new$col),mean)
    colnames(new.x)[-1]<-gene
    colnames(new.y)[-1]<-gene
    for (g in gene) {
      g.row=ggplot(data=new.x,aes(.data[['Group.1']],.data[[g]]))+   ## aes(col,-row)可以和切片图像方向一致
        geom_line(aes(col=.data[[g]]))+
        scale_color_gradient(low = hsv(0.58,0.92,0.92),high = hsv(1,1,1))+
        labs(title=paste0('Marginal Expression SVG: ',g))+
        xlab('index (by column axis)')+ylab('marginal expresson')+
        theme_bw()
      g.col=ggplot(data=new.y,aes(.data[['Group.1']],.data[[g]]))+   ## aes(col,-row)可以和切片图像方向一致
        geom_line(aes(col=.data[[g]]))+
        scale_color_gradient(low = hsv(0.58,0.92,0.92),high = hsv(1,1,1))+
        # labs(title=paste0('Marginal Expression SVG: ',g))+
        xlab('index (by row axis)')+ylab('marginal expresson')+
        theme_bw()
      
      
      gridExtra::grid.arrange(g.row,g.col,nrow=2)
    }
  }
  if(method=='mean'){
    cl.data=subset(data,select = gene)  ## subset data with given gene
    plot.cl=cbind(data[,1:2],apply(cl.data,1,mean))   ## calculate mean expression
    colnames(plot.cl)[3]<-'cluster'
    new=plot.cl
    new.x=aggregate(new[,-c(1:2)],list(new$row),mean)
    new.y=aggregate(new[,-c(1:2)],list(new$col),mean)
    g='x'
    g.row=ggplot(data=new.x,aes(.data[['Group.1']],.data[[g]]))+   ## aes(col,-row)可以和切片图像方向一致
      geom_line(aes(col=.data[[g]]))+
      scale_color_gradient(low = hsv(0.58,0.92,0.92),high = hsv(1,1,1),
                           name='value')+
      labs(title=paste0('Marginal Expression'))+
      xlab('index (by column axis)')+ylab('marginal expresson')+
      theme_bw()
    
    g.col=ggplot(data=new.y,aes(.data[['Group.1']],.data[[g]]))+   ## aes(col,-row)可以和切片图像方向一致
      geom_line(aes(col=.data[[g]]))+
      scale_color_gradient(low = hsv(0.58,0.92,0.92),high = hsv(1,1,1),
                           name='value')+
      # labs(title=paste0('Marginal Expression'))+
      xlab('index (by row axis)')+ylab('marginal expresson')+
      theme_bw()
    # print(gridExtra::grid.arrange(g.row,g.col,nrow=2))
    gridExtra::grid.arrange(g.row,g.col,nrow=2)
  }
}



#' @title title  3D plots for genes.
#' @param data A data frame that contains the data to be visualized.
#' The data format is the same as the parameter 'data' in heartsvg and svg.clust.
#' It contains gene coordinates and gene expression counts.
#' @param gene A vector, the gene or list of genes to be plotted.
#' @param type A character string. The type of the plot, can be 'scatter' or 'surface'.
#' If the type parameter is 'surface', a 3D surface plot will be drawn.
#' If the type parameter is 'scatter', a 3D scatter plot will be drawn."
#' @return  3D plots.
#' @export
svg.3Dplot=function(data,gene,type=NULL){

  if (length(gene)==1){
    cl.data=subset(data,select = gene)  ## subset data with given gene
    plot.cl=cbind(data[,1:2],cl.data)   ## calculate mean expression
    colnames(plot.cl)[3]<-gene

  }

  if(length(gene)>1){
    cl.data=base::subset(data,select = gene)  ## subset data with given gene
    plot.cl=cbind(data[,1:2],apply(cl.data,1,mean))   ## calculate mean expression
    colnames(plot.cl)[3]<-'cluster'
  }
  if(is.null(type)){
    stop('Missing the parameter type!')
  }

  if(type=='scatter'){
    print(plot_ly(x=plot.cl$col,y=(-plot.cl$row),
                  z=plot.cl[,3],
                  type="scatter3d", mode="markers",
                  color=plot.cl[,3]))
  }

  if(type=='surface'){
    ## first: smooth
    pp1=ppp(x=plot.cl$row,y=plot.cl$col,range(plot.cl$row),range(plot.cl$col),
            marks = plot.cl[,3])
    l1=Smooth.ppp(pp1)  ## spatstat.family
    xy=mesh(l1$yrow,y=l1$xcol)
    par(mar=c(2,6,2,6),xpd=F)## 下、左、上、右

    surf3D(x=xy$x, y=-xy$y,z=l1$v,
           col = ramp.col(col = c(hsv(5/9,0.73,0.94),hsv(1/6,0.6,1),hsv(1,1,1))),
           shade = 0.2,contour=F,alpha=0.9,
           bty='b',
           xlab = 'row',ylab='col',zlab='gene expression',
           main =paste0('3D-plot: ',colnames(plot.cl)[3]),
           clab = 'gene expression',scale=T)

  }
}






